package abstraction.version1;

public class TestGagnant {
	public static int P = Etat.PERSONNE;
	public static int O = Etat.ORDI;
	public static int H = Etat.HUMAIN;
	public static String[] noms = {"Etat.PERSONNE", "Etat.HUMAIN", "Etat.ORDI"};
	
	public static void main(String[] args) {
		int[][][] benchmark = {
			{	{P, P, P, P, P, P},
				{P, P, P, P, P, P},
				{P, P, P, P, P, P},
				{P, P, P, P, P, P},
				{P, P, P, P, P, P},
				{P, P, P, P, P, P},
				{P, P, P, P, P, P},
			},
			{	{H, H, H, H, P, P},
				{O, P, P, P, P, P},
				{O, P, P, P, P, P},
				{O, P, P, P, P, P},
				{P, P, P, P, P, P},
				{P, P, P, P, P, P},
				{P, P, P, P, P, P},
			},
			{	{H, H, H, P, P, P},
				{O, H, P, P, P, P},
				{O, P, P, P, P, P},
				{O, P, P, P, P, P},
				{O, P, P, P, P, P},
				{P, P, P, P, P, P},
				{P, P, P, P, P, P},
			},
			{	{O, H, H, P, P, P},
				{O, H, P, P, P, P},
				{O, H, P, P, P, P},
				{O, P, P, P, P, P},
				{P, P, P, P, P, P},
				{P, P, P, P, P, P},
				{P, P, P, P, P, P},
			},
			{	{O, H, H, P, P, P},
				{O, H, P, P, P, P},
				{O, H, P, P, P, P},
				{H, P, P, P, P, P},
				{H, P, P, P, P, P},
				{H, P, P, P, P, P},
				{O, O, O, O, P, P},
			},
			{	{O, H, H, P, P, P},
				{O, H, P, P, P, P},
				{O, H, P, P, P, P},
				{H, P, P, P, P, P},
				{H, P, P, P, P, P},
				{H, P, P, P, P, P},
				{H, O, O, O, P, P},
			},
			{	{O, H, H, P, P, P},
				{O, O, P, P, P, P},
				{O, H, O, P, P, P},
				{H, H, H, O, P, P},
				{O, P, P, P, P, P},
				{O, O, P, P, P, P},
				{H, H, H, O, P, P},
			},
			{	{H, H, H, P, P, P},
				{O, H, P, P, P, P},
				{O, O, H, P, P, P},
				{H, H, O, H, P, P},
				{O, P, P, P, P, P},
				{O, O, P, P, P, P},
				{H, H, H, O, P, P},
			},
			{	{H, H, H, P, P, P},
				{O, O, P, P, P, P},
				{O, O, O, P, P, P},
				{H, H, O, H, P, P},
				{O, P, H, P, P, P},
				{O, H, P, P, P, P},
				{H, H, H, O, P, P},
			},
			{	{H, H, H, P, P, P},
				{O, O, P, P, P, P},
				{O, O, H, P, P, P},
				{H, H, O, O, P, P},
				{O, P, O, P, P, P},
				{O, O, P, P, P, P},
				{O, H, H, O, P, P},
			},
			{	{H, H, H, P, P, P},
				{O, O, P, P, P, P},
				{H, O, H, P, P, P},
				{H, H, O, O, P, P},
				{H, P, H, P, P, P},
				{H, O, P, P, P, P},
				{O, H, H, O, P, P},
			},
			{	{H, H, H, P, P, P},
				{O, O, P, P, P, P},
				{O, O, H, P, P, P},
				{O, H, O, O, P, P},
				{O, P, H, P, P, P},
				{H, O, P, P, P, P},
				{O, H, H, O, P, P},
			},
			{	{H, O, H, H, H, H},
				{O, O, P, P, P, P},
				{O, O, H, P, P, P},
				{H, H, O, O, P, P},
				{O, P, H, P, P, P},
				{H, O, P, P, P, P},
				{O, H, H, O, P, P},
			},
			{	{H, H, O, O, O, O},
				{O, O, P, P, P, P},
				{O, O, H, P, P, P},
				{H, H, O, O, P, P},
				{O, P, H, P, P, P},
				{H, O, P, P, P, P},
				{O, H, H, O, P, P},
			},
			{	{O, H, H, H, H, O},
				{O, O, P, P, P, P},
				{O, O, H, P, P, P},
				{H, H, O, O, P, P},
				{O, P, H, P, P, P},
				{H, O, P, P, P, P},
				{O, H, H, O, P, P},
			},
			{	{H, O, O, O, O, H},
				{O, O, P, P, P, P},
				{O, O, H, P, P, P},
				{H, H, O, O, P, P},
				{O, P, H, P, P, P},
				{H, O, P, P, P, P},
				{O, H, H, O, P, P},
			},
			{	{H, O, H, O, O, H},
				{O, H, H, H, H, P},
				{O, O, H, P, P, P},
				{H, H, O, O, P, P},
				{O, P, H, P, P, P},
				{H, O, P, P, P, P},
				{O, H, H, O, P, P},
			},
			{	{H, O, H, O, O, H},
				{H, O, O, O, O, P},
				{O, O, H, P, P, P},
				{H, H, O, O, P, P},
				{O, P, H, P, P, P},
				{H, O, P, P, P, P},
				{O, H, H, O, P, P},
			},
			{	{H, O, H, O, O, H},
				{H, O, H, H, H, H},
				{O, O, H, P, P, P},
				{H, H, O, O, P, P},
				{O, P, H, P, P, P},
				{H, O, P, P, P, P},
				{O, H, H, O, P, P},
			},
			{	{H, O, H, O, O, H},
				{H, H, O, O, O, O},
				{O, O, H, P, P, P},
				{H, H, O, O, P, P},
				{O, P, H, P, P, P},
				{H, O, P, P, P, P},
				{O, H, H, O, P, P},
			},
			{	{H, O, H, H, O, H},
				{H, H, O, O, H, O},
				{O, H, O, O, O, O},
				{H, H, O, O, P, P},
				{O, P, H, P, P, P},
				{H, O, P, P, P, P},
				{O, H, H, O, P, P},
			},
			{	{H, O, H, H, O, H},
				{H, H, O, O, H, O},
				{O, O, H, H, H, H},
				{H, H, O, O, P, P},
				{O, P, H, P, P, P},
				{H, O, P, P, P, P},
				{O, H, H, O, P, P},
			},
			{	{H, O, H, H, O, H},
				{H, H, O, O, H, O},
				{O, O, O, H, H, H},
				{H, H, O, O, P, P},
				{O, P, H, P, P, P},
				{H, O, P, P, P, P},
				{O, O, H, H, H, H},
			},
			{	{H, O, H, H, O, H},
				{H, H, O, O, H, O},
				{O, O, O, H, H, H},
				{H, H, H, O, P, P},
				{O, P, H, P, P, P},
				{H, O, P, P, P, P},
				{O, O, H, O, H, H},
			},
			{	{H, O, H, H, O, O},
				{H, H, O, O, O, H},
				{O, O, H, O, H, H},
				{H, H, O, O, P, P},
				{O, P, H, P, P, P},
				{H, O, P, P, P, P},
				{O, O, H, O, H, H},
			},
			{	{H, O, H, H, O, O},
				{H, H, O, O, H, H},
				{O, O, H, O, H, H},
				{H, H, O, O, H, P},
				{O, P, H, H, P, P},
				{H, O, H, P, P, P},
				{O, O, H, O, H, H},
			},
			{	{H, O, H, H, O, O},
				{H, H, H, O, H, H},
				{O, O, H, O, H, H},
				{H, H, O, O, O, H},
				{O, P, H, H, O, H},
				{H, O, H, P, P, P},
				{O, O, H, O, H, H},
			},
			{	{H, O, H, H, O, O},
				{H, H, H, O, H, O},
				{O, O, H, O, H, O},
				{H, H, O, O, H, O},
				{O, P, H, H, O, H},
				{H, O, H, P, P, P},
				{O, O, H, O, H, H},
			},
			{	{H, O, H, H, O, H},
				{H, H, H, O, H, O},
				{O, O, H, O, H, O},
				{H, H, O, O, H, O},
				{O, P, H, H, O, O},
				{H, O, H, P, P, P},
				{O, O, H, O, H, H},
			},
			{	{H, O, H, H, O, H},
				{H, H, H, O, H, H},
				{O, O, H, O, H, O},
				{H, H, O, O, H, O},
				{O, P, H, H, O, O},
				{H, O, H, O, H, O},
				{O, O, H, O, H, H},
			},
			{	{H, O, H, H, O, H},
				{H, H, H, O, H, H},
				{O, O, H, O, H, H},
				{H, H, O, O, H, O},
				{O, P, H, H, O, O},
				{H, O, O, O, H, O},
				{O, O, H, O, H, O},
			},
			{	{H, O, H, H, O, H},
				{H, H, H, O, H, H},
				{O, O, H, O, H, O},
				{H, H, O, O, H, H},
				{O, P, H, H, O, H},
				{H, O, O, O, H, H},
				{O, O, H, O, H, H},
			},
			{	{H, O, H, H, O, H},
				{H, H, H, O, H, H},
				{O, O, H, O, H, O},
				{H, H, O, O, H, H},
				{O, P, H, H, O, H},
				{H, O, O, O, H, O},
				{O, O, H, O, H, H},
			},
			{	{H, O, H, H, O, H},
				{H, H, O, O, O, H},
				{O, O, H, H, H, O},
				{H, H, H, O, H, H},
				{O, P, H, H, O, H},
				{H, O, O, O, H, O},
				{O, O, H, O, H, H},
			},
			{	{H, O, H, H, O, H},
				{H, H, O, O, H, H},
				{O, H, O, H, O, O},
				{H, H, O, O, O, H},
				{O, P, H, O, H, H},
				{H, O, H, O, O, O},
				{O, H, O, H, H, O},
			},
			{	{H, O, H, H, O, H},
				{H, H, O, O, H, H},
				{O, H, O, H, O, O},
				{H, H, O, O, O, H},
				{O, P, H, O, H, H},
				{H, O, H, O, O, O},
				{O, H, O, H, H, H},
			},
			{	{H, O, H, H, O, H},
				{H, H, O, O, H, H},
				{O, H, O, H, O, O},
				{H, H, O, O, O, H},
				{O, P, H, O, H, H},
				{H, O, H, O, O, O},
				{O, O, H, H, H, H},
			},
			
		};
		int[] oracle = {0,1,2,2,2,1,2,1,1,2,1,2,1,2,1,2,1,2,1,2,2,1,1,1,2,1,1,2,2,2,2,1,0,1,2,0,1};
		boolean erreur = false;

		for (int i=0; !erreur && i<benchmark.length; i++) {
			Etat e = new Etat(benchmark[i]);
			erreur = e.gagnant()!=oracle[i];
			if (erreur) {
				System.out.println("Aie... sur la grille :");
				System.out.println(e);
				System.out.println(" la methode gagnant() retourne "+noms[e.gagnant()]+" au lieu de "+noms[oracle[i]]);
			}
		}
		if (!erreur) {
			System.out.println("Ok. Votre methode gagnant() passe le test avec succes.");
		}
		
	}

}
