package labo1.Hibernate.src;

// default package
// Generated 4 juin 2021 à 20:24:20 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Abonnement generated by hbm2java
 */
public class Abonnement implements java.io.Serializable {

	private String codeabo;
	private int nbpretmax;
	private Integer dureepretmax;
	private Set clients = new HashSet(0);

	public Abonnement() {
	}

	public Abonnement(String codeabo, int nbpretmax) {
		this.codeabo = codeabo;
		this.nbpretmax = nbpretmax;
	}

	public Abonnement(String codeabo, int nbpretmax, Integer dureepretmax, Set clients) {
		this.codeabo = codeabo;
		this.nbpretmax = nbpretmax;
		this.dureepretmax = dureepretmax;
		this.clients = clients;
	}

	public String getCodeabo() {
		return this.codeabo;
	}

	public void setCodeabo(String codeabo) {
		this.codeabo = codeabo;
	}

	public int getNbpretmax() {
		return this.nbpretmax;
	}

	public void setNbpretmax(int nbpretmax) {
		this.nbpretmax = nbpretmax;
	}

	public Integer getDureepretmax() {
		return this.dureepretmax;
	}

	public void setDureepretmax(Integer dureepretmax) {
		this.dureepretmax = dureepretmax;
	}

	public Set getClients() {
		return this.clients;
	}

	public void setClients(Set clients) {
		this.clients = clients;
	}

}
