package labo1.Hibernate.src;

// default package
// Generated 4 juin 2021 à 20:24:20 by Hibernate Tools 5.4.7.Final

/**
 * Acteurfilms generated by hbm2java
 */
public class Acteurfilms implements java.io.Serializable {

	private ActeurfilmsId id;
	private Artiste artiste;
	private Film film;
	private String prenompersonnage;
	private String nompersonnage;

	public Acteurfilms() {
	}

	public Acteurfilms(ActeurfilmsId id, Artiste artiste, Film film) {
		this.id = id;
		this.artiste = artiste;
		this.film = film;
	}

	public Acteurfilms(ActeurfilmsId id, Artiste artiste, Film film, String prenompersonnage, String nompersonnage) {
		this.id = id;
		this.artiste = artiste;
		this.film = film;
		this.prenompersonnage = prenompersonnage;
		this.nompersonnage = nompersonnage;
	}

	public ActeurfilmsId getId() {
		return this.id;
	}

	public void setId(ActeurfilmsId id) {
		this.id = id;
	}

	public Artiste getArtiste() {
		return this.artiste;
	}

	public void setArtiste(Artiste artiste) {
		this.artiste = artiste;
	}

	public Film getFilm() {
		return this.film;
	}

	public void setFilm(Film film) {
		this.film = film;
	}

	public String getPrenompersonnage() {
		return this.prenompersonnage;
	}

	public void setPrenompersonnage(String prenompersonnage) {
		this.prenompersonnage = prenompersonnage;
	}

	public String getNompersonnage() {
		return this.nompersonnage;
	}

	public void setNompersonnage(String nompersonnage) {
		this.nompersonnage = nompersonnage;
	}

}
