package labo1.Hibernate.src;

// default package
// Generated 4 juin 2021 à 20:24:20 by Hibernate Tools 5.4.7.Final

/**
 * ActeurfilmsId generated by hbm2java
 */
public class ActeurfilmsId implements java.io.Serializable {

	private int noartiste;
	private int idFilm;

	public ActeurfilmsId() {
	}

	public ActeurfilmsId(int noartiste, int idFilm) {
		this.noartiste = noartiste;
		this.idFilm = idFilm;
	}

	public int getNoartiste() {
		return this.noartiste;
	}

	public void setNoartiste(int noartiste) {
		this.noartiste = noartiste;
	}

	public int getIdFilm() {
		return this.idFilm;
	}

	public void setIdFilm(int idFilm) {
		this.idFilm = idFilm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ActeurfilmsId))
			return false;
		ActeurfilmsId castOther = (ActeurfilmsId) other;

		return (this.getNoartiste() == castOther.getNoartiste()) && (this.getIdFilm() == castOther.getIdFilm());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNoartiste();
		result = 37 * result + this.getIdFilm();
		return result;
	}

}
