package labo1.Hibernate.src;

// default package
// Generated 4 juin 2021 à 20:24:20 by Hibernate Tools 5.4.7.Final

/**
 * Bandeannonce generated by hbm2java
 */
public class Bandeannonce implements java.io.Serializable {

	private BandeannonceId id;
	private Film film;

	public Bandeannonce() {
	}

	public Bandeannonce(BandeannonceId id) {
		this.id = id;
	}

	public BandeannonceId getId() {
		return this.id;
	}

	public void setId(BandeannonceId id) {
		this.id = id;
	}

	public Film getFilm() {
		return this.film;
	}

	public void setFilm(Film film) {
		this.film = film;
	}


}
