package labo1.Hibernate.src;

// default package
// Generated 4 juin 2021 à 20:24:20 by Hibernate Tools 5.4.7.Final

/**
 * BandeannonceId generated by hbm2java
 */
public class BandeannonceId implements java.io.Serializable {

	private String lien;
	private int idFilm;

	public BandeannonceId() {
	}

	public BandeannonceId(String lien, int idFilm) {
		this.lien = lien;
		this.idFilm = idFilm;
	}

	public String getLien() {
		return this.lien;
	}

	public void setLien(String lien) {
		this.lien = lien;
	}

	public int getIdFilm() {
		return this.idFilm;
	}

	public void setIdFilm(int idFilm) {
		this.idFilm = idFilm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BandeannonceId))
			return false;
		BandeannonceId castOther = (BandeannonceId) other;

		return ((this.getLien() == castOther.getLien()) || (this.getLien() != null && castOther.getLien() != null
				&& this.getLien().equals(castOther.getLien()))) && (this.getIdFilm() == castOther.getIdFilm());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLien() == null ? 0 : this.getLien().hashCode());
		result = 37 * result + this.getIdFilm();
		return result;
	}

}
