package labo1.Hibernate.src;

// default package
// Generated 4 juin 2021 à 20:24:20 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client implements java.io.Serializable {

	private int idPersonne;
	private Abonnement abonnement;
	private Personne personne;
	private int nbfilmsactuellementempruntes;
	private Cartecredit cartecredit;
	private Set prets = new HashSet(0);

	public Client() {
	}

	public Client(Abonnement abonnement, Personne personne, int nbfilmsactuellementempruntes) {
		this.abonnement = abonnement;
		this.personne = personne;
		this.nbfilmsactuellementempruntes = nbfilmsactuellementempruntes;
	}

	public Client(Abonnement abonnement, Personne personne, int nbfilmsactuellementempruntes, Cartecredit cartecredit,
			Set prets) {
		this.abonnement = abonnement;
		this.personne = personne;
		this.nbfilmsactuellementempruntes = nbfilmsactuellementempruntes;
		this.cartecredit = cartecredit;
		this.prets = prets;
	}

	public int getIdPersonne() {
		return this.idPersonne;
	}

	public void setIdPersonne(int idPersonne) {
		this.idPersonne = idPersonne;
	}

	public Abonnement getAbonnement() {
		return this.abonnement;
	}

	public void setAbonnement(Abonnement abonnement) {
		this.abonnement = abonnement;
	}

	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	public int getNbfilmsactuellementempruntes() {
		return this.nbfilmsactuellementempruntes;
	}

	public void setNbfilmsactuellementempruntes(int nbfilmsactuellementempruntes) {
		this.nbfilmsactuellementempruntes = nbfilmsactuellementempruntes;
	}

	public Cartecredit getCartecredit() {
		return this.cartecredit;
	}

	public void setCartecredit(Cartecredit cartecredit) {
		this.cartecredit = cartecredit;
	}

	public Set getPrets() {
		return this.prets;
	}

	public void setPrets(Set prets) {
		this.prets = prets;
	}

}
