package labo1.Hibernate.src;

// default package
// Generated 4 juin 2021 à 20:24:20 by Hibernate Tools 5.4.7.Final

/**
 * Bandeannonce generated by hbm2java
 */
public class Correlationfilms implements java.io.Serializable {

	private CorrelationfilmsId id;
    private Double correlation;

	public Correlationfilms() {
	}

	public Correlationfilms(CorrelationfilmsId id) {
		this.id = id;
	}

	public CorrelationfilmsId getId() {
		return this.id;
	}

	public void setId(CorrelationfilmsId id) {
		this.id = id;
	}

    public Double getCorrelation() {
		return this.correlation;
	}

	public void setCorrelation(Double correlation) {
		this.correlation = correlation;
	}


}
