package labo1.Hibernate.src;

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Personne generated by hbm2java
 */
public class Dimensiontemps implements java.io.Serializable {

	private int iddatelocation;
	private Timestamp datelocation;
	private Integer heurejour;
	private String joursemaine;
	private String moisannee;
	private Set faitslocationfilms = new HashSet(0);

	public Dimensiontemps() {
	}

	public Dimensiontemps(int iddatelocation, Timestamp datelocation, Integer heurejour, String joursemaine, String moisannee) {
		this.iddatelocation = iddatelocation;
		this.datelocation = datelocation;
		this.heurejour = heurejour;
		this.joursemaine = joursemaine;
		this.moisannee = moisannee;
	}

	public Dimensiontemps(int iddatelocation, Timestamp datelocation, Integer heurejour, String joursemaine, String moisannee, Set faitslocationfilms) {
		this.iddatelocation = iddatelocation;
		this.datelocation = datelocation;
		this.heurejour = heurejour;
		this.joursemaine = joursemaine;
		this.moisannee = moisannee;
		this.faitslocationfilms = faitslocationfilms;
	}

	public int getiddatelocation() {
		return this.iddatelocation;
	}

	public void setiddatelocation(int iddatelocation) {
		this.iddatelocation = iddatelocation;
	}

	public Timestamp getdatelocation() {
		return this.datelocation;
	}

	public void setdatelocation(Timestamp datelocation) {
		this.datelocation = datelocation;
	}

	public Integer getheurejour() {
		return this.heurejour;
	}

	public void setheurejour(Integer heurejour) {
		this.heurejour = heurejour;
	}

	public String getjoursemaine() {
		return this.joursemaine;
	}

	public void setjoursemaine(String joursemaine) {
		this.joursemaine = joursemaine;
	}

	public String getmoisannee() {
		return this.moisannee;
	}

	public void setmoisannee(String moisannee) {
		this.moisannee = moisannee;
	}

	public Set getfaitslocationfilms() {
		return this.faitslocationfilms;
	}

	public void setfaitslocationfilms(Set faitslocationfilms) {
		this.faitslocationfilms = faitslocationfilms;
	}

}