package labo1.Hibernate.src;

// default package
// Generated 4 juin 2021 à 20:24:20 by Hibernate Tools 5.4.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Personne generated by hbm2java
 */
public class Dimensionclient implements java.io.Serializable {

	private int idclient;
	private String nomcomplet;
	private Integer groupeage;
	private String courriel;
	private Date datepremierelocation;
	private String codepostal;
	private String ville;
	private String province;
	private Set faitslocationfilms = new HashSet(0);

	public Dimensionclient() {
	}

	public Dimensionclient(int idclient, String nomcomplet, Integer groupeage, String courriel,
			Date datepremierelocation, String codepostal, String ville, String province) {
		this.idclient = idclient;
		this.nomcomplet = nomcomplet;
		this.groupeage = groupeage;
		this.courriel = courriel;
		this.datepremierelocation = datepremierelocation;
		this.codepostal = codepostal;
		this.ville = ville;
		this.province = province;
	}

	public Dimensionclient(int idclient, String nomcomplet, Integer groupeage, String courriel,
	Date datepremierelocation, String codepostal, String ville, String province, Set faitslocationfilms) {
		this.idclient = idclient;
		this.nomcomplet = nomcomplet;
		this.groupeage = groupeage;
		this.courriel = courriel;
		this.datepremierelocation = datepremierelocation;
		this.codepostal = codepostal;
		this.ville = ville;
		this.province = province;
		this.faitslocationfilms = faitslocationfilms;
	}

	public int getidclient() {
		return this.idclient;
	}

	public void setidclient(int idclient) {
		this.idclient = idclient;
	}

	public String getnomcomplet() {
		return this.nomcomplet;
	}

	public void setnomcomplet(String nomcomplet) {
		this.nomcomplet = nomcomplet;
	}


	public String getcourriel() {
		return this.courriel;
	}

	public void setcourriel(String courriel) {
		this.courriel = courriel;
	}

	public Integer getgroupeage() {
		return this.groupeage;
	}

	public void setgroupeage(int groupeage) {
		this.groupeage = groupeage;
	}

	public Date getdatepremierelocation() {
		return this.datepremierelocation;
	}

	public void setdatepremierelocation(Date datepremierelocation) {
		this.datepremierelocation = datepremierelocation;
	}

	public String getville() {
		return this.ville;
	}

	public void setville(String ville) {
		this.ville = ville;
	}

	public String getprovince() {
		return this.province;
	}

	public void setprovince(String province) {
		this.province = province;
	}

	public String getcodepostal() {
		return this.codepostal;
	}

	public void setcodepostal(String codepostal) {
		this.codepostal = codepostal;
	}

	public Set getfaitslocationfilms() {
		return this.faitslocationfilms;
	}

	public void setfaitslocationfilms(Set faitslocationfilms) {
		this.faitslocationfilms = faitslocationfilms;
	}

}