package labo1.Hibernate.src;

import java.util.HashSet;
import java.util.Set;

/**
 * Personne generated by hbm2java
 */
public class Dimensionfilm implements java.io.Serializable {

	private int idfilm;
	private String titre;
	private Integer anneesortie;
	private String paysorigine;
	private Integer actionfilm;
	private Integer animation;
	private Integer aventure;
	private Integer biography;
    private Integer comedy;
    private Integer drama;
    private Integer family;
    private Integer fantasy;
    private Integer romance;
    private Integer scifi;
    private Integer thriller;
	private Set faitslocationfilms = new HashSet(0);

	public Dimensionfilm() {
	}

	public Dimensionfilm(int idfilm, String titre, Integer anneesortie, String paysorigine,
            Integer actionfilm, Integer animation, Integer aventure, Integer biography,
            Integer comedy, Integer drama, Integer family, Integer fantasy, Integer romance,
            Integer scifi, Integer thriller) {
		this.idfilm = idfilm;
		this.titre = titre;
		this.anneesortie = anneesortie;
		this.paysorigine = paysorigine;
		this.actionfilm = actionfilm;
		this.animation = animation;
		this.aventure = aventure;
		this.biography = biography;
        this.comedy = comedy;
        this.drama = drama;
        this.family = family;
        this.romance = romance;
        this.scifi = scifi;
        this.thriller = thriller;
	}

	public Dimensionfilm(int idfilm, String titre, Integer anneesortie, String paysorigine,
    Integer actionfilm, Integer animation, Integer aventure, Integer biography,
    Integer comedy, Integer drama, Integer family, Integer fantasy, Integer romance,
    Integer scifi, Integer thriller, Set faitslocationfilms) {
		this.idfilm = idfilm;
		this.titre = titre;
		this.anneesortie = anneesortie;
		this.paysorigine = paysorigine;
		this.actionfilm = actionfilm;
		this.animation = animation;
		this.aventure = aventure;
		this.biography = biography;
        this.comedy = comedy;
        this.drama = drama;
        this.family = family;
        this.romance = romance;
        this.scifi = scifi;
        this.thriller = thriller;
		this.faitslocationfilms = faitslocationfilms;
	}

	public int getidfilm() {
		return this.idfilm;
	}

	public void setidfilm(int idfilm) {
		this.idfilm = idfilm;
	}

	public String gettitre() {
		return this.titre;
	}

	public void settitre(String titre) {
		this.titre = titre;
	}


	public Integer getanneesortie() {
		return this.anneesortie;
	}

	public void setanneesortie(Integer anneesortie) {
		this.anneesortie = anneesortie;
	}

	public String getpaysorigine() {
		return this.paysorigine;
	}

	public void setpaysorigine(String paysorigine) {
		this.paysorigine = paysorigine;
	}

    public Integer getactionfilm() {
		return this.actionfilm;
	}

	public void setactionfilm(Integer action) {
		this.actionfilm = action;
	}

    public Integer getanimation() {
		return this.animation;
	}

	public void setanimation(Integer animation) {
		this.animation = animation;
	}

    public Integer getaventure() {
		return this.aventure;
	}

	public void setaventure(Integer aventure) {
		this.aventure = aventure;
	}

    public Integer getbiography() {
		return this.biography;
	}

	public void setbiography(Integer biography) {
		this.biography = biography;
	}

    public Integer getcomedy() {
		return this.comedy;
	}

	public void setcomedy(Integer comedy) {
		this.comedy = comedy;
	}

    public Integer getdrama() {
		return this.drama;
	}

	public void setdrama(Integer drama) {
		this.drama = drama;
	}

    public Integer getfamily() {
		return this.family;
	}

	public void setfamily(Integer family) {
		this.family = family;
	}

    public Integer getfantasy() {
		return this.fantasy;
	}

	public void setfantasy(Integer fantasy) {
		this.fantasy = fantasy;
	}

    public Integer getromance() {
		return this.romance;
	}

	public void setromance(Integer romance) {
		this.romance = romance;
	}

    public Integer getscifi() {
		return this.scifi;
	}

	public void setscifi(Integer scifi) {
		this.scifi = scifi;
	}

    public Integer getthriller() {
		return this.thriller;
	}

	public void setthriller(Integer thriller) {
		this.thriller = thriller;
	}

	public Set getfaitslocationfilms() {
		return this.faitslocationfilms;
	}

	public void setfaitslocationfilms(Set faitslocationfilms) {
		this.faitslocationfilms = faitslocationfilms;
	}

}