package labo1.Hibernate.src;

// default package
// Generated 4 juin 2021 à 20:24:20 by Hibernate Tools 5.4.7.Final

/**
 * Employe generated by hbm2java
 */
public class Employe implements java.io.Serializable {

	private int matricule;
	private Personne personne;

	public Employe() {
	}

	public Employe(int matricule, Personne personne) {
		this.matricule = matricule;
		this.personne = personne;
	}

	public int getMatricule() {
		return this.matricule;
	}

	public void setMatricule(int matricule) {
		this.matricule = matricule;
	}

	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

}
