package labo1.Hibernate.src;

/**
 * Exemplaire generated by hbm2java
 */
public class Exemplaire implements java.io.Serializable {

	private int nocopie;
	private Film film;
	private Pret pret;
	private String statut;

	public Exemplaire() {
	}

	public Exemplaire(int nocopie, Film film, String statut) {
		this.nocopie = nocopie;
		this.film = film;
		this.statut = statut;
	}

	public Exemplaire(int nocopie, Film film, Pret pret, String statut) {
		this.nocopie = nocopie;
		this.film = film;
		this.pret = pret;
		this.statut = statut;
	}

	public int getNocopie() {
		return this.nocopie;
	}

	public void setNocopie(int nocopie) {
		this.nocopie = nocopie;
	}

	public Film getFilm() {
		return this.film;
	}

	public void setFilm(Film film) {
		this.film = film;
	}

	public Pret getPret() {
		return this.pret;
	}

	public void setPret(Pret pret) {
		this.pret = pret;
	}

	public String getStatut() {
		return this.statut;
	}

	public void setStatut(String statut) {
		this.statut = statut;
	}

}
