package labo1.Hibernate.src;

// default package
// Generated 4 juin 2021 à 20:24:20 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Film generated by hbm2java
 */
public class Film implements java.io.Serializable {

	private int idFilm;
	private String titre;
	private Integer anneeproduction;
	private String paysproduction;
	private String langueoriginale;
	private Integer duree;
	private String resumefilm;
	private String affiche;
	private int quantitestock;
	private Set exemplaires = new HashSet(0);
	private Set artistes = new HashSet(0);  // ce sont les realisateurs
	private Set acteurfilmses = new HashSet(0); // ce sont les acteurs
	private Set scenaristes = new HashSet(0);
	private Set genres = new HashSet(0);
	private Set bandeannonces = new HashSet(0);

	public Film() {
	}

	public Film(int idFilm, String titre, int quantitestock) {
		this.idFilm = idFilm;
		this.titre = titre;
		this.quantitestock = quantitestock;
	}

	public Film(int idFilm, String titre, Integer anneeproduction, String paysproduction, String langueoriginale,
			Integer duree, String resumefilm, String affiche, int quantitestock, Set exemplaires, Set artistes,
			Set acteurfilmses, Set scenaristes, Set genres, Set bandeannonces) {
		this.idFilm = idFilm;
		this.titre = titre;
		this.anneeproduction = anneeproduction;
		this.paysproduction = paysproduction;
		this.langueoriginale = langueoriginale;
		this.duree = duree;
		this.resumefilm = resumefilm;
		this.affiche = affiche;
		this.quantitestock = quantitestock;
		this.exemplaires = exemplaires;
		this.artistes = artistes;
		this.acteurfilmses = acteurfilmses;
		this.scenaristes = scenaristes;
		this.genres = genres;
		this.bandeannonces = bandeannonces;
	}

	public int getIdFilm() {
		return this.idFilm;
	}

	public void setIdFilm(int idFilm) {
		this.idFilm = idFilm;
	}

	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	public Integer getAnneeproduction() {
		return this.anneeproduction;
	}

	public void setAnneeproduction(Integer anneeproduction) {
		this.anneeproduction = anneeproduction;
	}

	public String getPaysproduction() {
		return this.paysproduction;
	}

	public void setPaysproduction(String paysproduction) {
		this.paysproduction = paysproduction;
	}

	public String getLangueoriginale() {
		return this.langueoriginale;
	}

	public void setLangueoriginale(String langueoriginale) {
		this.langueoriginale = langueoriginale;
	}

	public Integer getDuree() {
		return this.duree;
	}

	public void setDuree(Integer duree) {
		this.duree = duree;
	}

	public String getResumefilm() {
		return this.resumefilm;
	}

	public void setResumefilm(String resumefilm) {
		this.resumefilm = resumefilm;
	}

	public String getAffiche() {
		return this.affiche;
	}

	public void setAffiche(String affiche) {
		this.affiche = affiche;
	}

	public int getQuantitestock() {
		return this.quantitestock;
	}

	public void setQuantitestock(int quantitestock) {
		this.quantitestock = quantitestock;
	}

	public Set getExemplaires() {
		return this.exemplaires;
	}

	public void setExemplaires(Set exemplaires) {
		this.exemplaires = exemplaires;
	}

	public Set getArtistes() {
		return this.artistes;
	}

	public void setArtistes(Set artistes) {
		this.artistes = artistes;
	}

	public Set getActeurfilmses() {
		return this.acteurfilmses;
	}

	public void setActeurfilmses(Set acteurfilmses) {
		this.acteurfilmses = acteurfilmses;
	}

	public Set getScenaristes() {
		return this.scenaristes;
	}

	public void setScenaristes(Set scenaristes) {
		this.scenaristes = scenaristes;
	}

	public Set getGenres() {
		return this.genres;
	}

	public void setGenres(Set genres) {
		this.genres = genres;
	}

	public Set getBandeannonces() {
		return this.bandeannonces;
	}
	
	public void setBandeannonces(Set bandeannonces) {
		this.bandeannonces = bandeannonces;
	}

}
