package labo1.Hibernate.src;

// default package
// Generated 4 juin 2021 à 20:24:20 by Hibernate Tools 5.4.7.Final

import java.util.Date;

/**
 * Pretarchive generated by hbm2java
 */
public class Pretarchive implements java.io.Serializable {

	private int idPret;
	private Pret pret;
	private Date dateretour;

	public Pretarchive() {
	}

	public Pretarchive(Pret pret, Date dateretour) {
		this.pret = pret;
		this.dateretour = dateretour;
	}

	public int getIdPret() {
		return this.idPret;
	}

	public void setIdPret(int idPret) {
		this.idPret = idPret;
	}

	public Pret getPret() {
		return this.pret;
	}

	public void setPret(Pret pret) {
		this.pret = pret;
	}

	public Date getDateretour() {
		return this.dateretour;
	}

	public void setDateretour(Date dateretour) {
		this.dateretour = dateretour;
	}

}
