package labo1.Hibernate.src;

// default package
// Generated 4 juin 2021 à 20:24:20 by Hibernate Tools 5.4.7.Final

/**
 * Pretencours generated by hbm2java
 */
public class Pretencours implements java.io.Serializable {

	private int idPret;
	private Pret pret;
	private boolean enretard;

	public Pretencours() {
	}

	public Pretencours(Pret pret, boolean enretard) {
		this.pret = pret;
		this.enretard = enretard;
	}

	public int getIdPret() {
		return this.idPret;
	}

	public void setIdPret(int idPret) {
		this.idPret = idPret;
	}

	public Pret getPret() {
		return this.pret;
	}

	public void setPret(Pret pret) {
		this.pret = pret;
	}

	public boolean isEnretard() {
		return this.enretard;
	}

	public void setEnretard(boolean enretard) {
		this.enretard = enretard;
	}

}
