package labo1.Hibernate.src;

// default package
// Generated 4 juin 2021 à 20:24:20 by Hibernate Tools 5.4.7.Final

/**
 * Scenariste generated by hbm2java
 */
public class Scenariste implements java.io.Serializable {

	private ScenaristeId id;
	private Film film;

	public Scenariste() {
	}

	public Scenariste(ScenaristeId id, Film film) {
		this.id = id;
		this.film = film;
	}

	public ScenaristeId getId() {
		return this.id;
	}

	public void setId(ScenaristeId id) {
		this.id = id;
	}

	public Film getFilm() {
		return this.film;
	}

	public void setFilm(Film film) {
		this.film = film;
	}

}
